config/routes.rb
Rails.application.routes.draw do
  resources :songs

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :user_songs
  has_many :users, through: :user_songs 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true
  has_many :user_songs
  has_many :songs, through: :user_songs 
end

app/models/user_song.rb
class UserSong < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  def current_user
  
    @current_user || User.find(session[:user_id]) if session[:user_id]

  end
  
  def redirect_unless_current_user
    redirect_to login_path unless current_user.present? 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash[:errors] = "Invalid Login."
      render :new
    end
  end

  def destroy
    flash[:logout] = "Goodbye"
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :destroy, :update]
  before_action :redirect_unless_current_user, only: [:index]
  
  def index

    # @songs = Song.all    
    @songs = current_user.songs  
  end

  def show
    # @song = Song.find(params[:id])
  end

  def new
    if current_user.nil?
      redirect_to login_path, alert: "You Must Login First"
    else
      @song = current_user.songs.create
    end
    # if !current_user.nil?
    #   @song = current_user.songs.create
    # else
    #   @song = Song.new 
    # end
  end

  def create
    song = Song.new(song_params)

    if song.save
      redirect_to song
    else
      render :new
    end
  end

  def edit
    # @song = Song.find(params[:id])
  end

  def update
    # @song = Song.find(params[:id])
    if @song.update(song_params)
      redirect_to @song
    else
      render :edit
    end
  end

  def destroy
    # @song = Song.find(params[:id]) 
    @song.destroy
    redirect_to songs_path
  end

  private

  def set_song
     @song = Song.find(params[:id])  
  end

  def song_params
    params.require(:song).permit(:title, :artist)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    redirect_unless_current_user
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    redirect_unless_current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body> 
  <% if current_user.present? %>
    <p>logged in as <%= current_user.username %></p>
    <%= button_to 'log out', logout_path, method: :delete, class: "button" %>

    <%end %>
    <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <%= f.label :artist %>
  <%= f.text_field :artist %>
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: "artist"%>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit this Song</h1>

<%= render 'form' %>

app/views/songs/index.html.erb
<h1>All Songs (index)</h1>
<ol>
<% @songs.each do |song| %>
  <li><%= link_to song.title, song  %> by <%= song.artist%></li>
  <% end %>
</ol>
<%= link_to "New Song", new_song_path %>
<%= link_to "Profile", user_path(current_user.id) %>

app/views/songs/new.html.erb
<h1>Create a New Song! </h1>
<%= render 'form' %>

app/views/songs/show.html.erb
<h1><%= @song.title  %></h1> 
<h3><%= @song.artist %></h3>

<%= link_to "Edit Song", edit_song_path(@song)%>
<%= link_to "Delete Song", song_path(@song), method: :delete %>

<p><%= link_to "All Songs", songs_path   %></p>

app/views/users/index.html.erb
<h1>Users </h1>
<ul>
  <% if @users.all.count == 0 %>
    <p><%="No Users Have been Created"%></p>
    <% else %>
    <% @users.each do |user| %>
  <li><%= user.username  %><li>
    <% end %>
    <% end %>
  </ul>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.username %></h1>
<h3>Here are the artists you are currently following:</h3>
<ol>
<% current_user.songs.each do |song| %>
  <li><%= song.artist%></li>
  <% end %>
</ol>

<p><%= button_to 'My Songs', songs_path, method: :get, class: "button" %></p>